### ISSUE TITLE
你好，能一起讨论一下t2vec的代码实现吗

### ISSUE THREAD

**Issue by duanshoujian** [C-Harlin/trjsr#1]

**Comment by C-Harlin** [comment]
你好，我觉得原作者的文档、注释都写得挺清楚的，复现和理解都没有障碍

**Comment by duanshoujian** [comment]
您好！可能我对于julia这个语言理解有点障碍。我想问问您关于makeVocab这个函数，作者是把轨迹经纬度数据如何处理了呢？请问region.vocab_size指的是什么？感谢&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "C-Harlin/trjsr"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月3日(星期四) 上午9:29
收件人:&nbsp;"C-Harlin/trjsr"<trjsr@noreply.github.com&gt;;
抄送:&nbsp;"冰糖葫芦小豆子"<1296783000@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [C-Harlin/trjsr] 你好，能一起讨论一下t2vec的代码实现吗 (#1)





 
你好，我觉得原作者的文档、注释都写得挺清楚的，复现和理解都没有障碍

**Comment by C-Harlin** [comment]
作者将经纬度转化成为cell id，相关函数写得很清晰。这部分原文中有解释，建议你再多看看论文的相关部分。如果代码初看不懂的话，建议忽略技术细节，理解其功能即可。

**Comment by duanshoujian** [comment]
好的，谢谢您 能在问一下关于作者训练的时候的参数vocal_size 作者给的是18664是什么意思吗？我关键就是在变成词汇表的时候不太理解作者的思想。其他部分到没有什么很疑惑的地方


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "C-Harlin/trjsr"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月4日(星期五) 晚上9:38
收件人:&nbsp;"C-Harlin/trjsr"<trjsr@noreply.github.com&gt;;
抄送:&nbsp;"冰糖葫芦小豆子"<1296783000@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [C-Harlin/trjsr] 你好，能一起讨论一下t2vec的代码实现吗 (#1)





 
作者将经纬度转化成为cell id，相关函数写得很清晰。这部分原文中有解释，建议你再多看看论文的相关部分。如果代码初看不懂的话，建议忽略技术细节，理解其功能即可。

**Comment by duanshoujian** [comment]
这个地方




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "C-Harlin/trjsr"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月4日(星期五) 晚上9:38
收件人:&nbsp;"C-Harlin/trjsr"<trjsr@noreply.github.com&gt;;
抄送:&nbsp;"冰糖葫芦小豆子"<1296783000@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [C-Harlin/trjsr] 你好，能一起讨论一下t2vec的代码实现吗 (#1)





 
作者将经纬度转化成为cell id，相关函数写得很清晰。这部分原文中有解释，建议你再多看看论文的相关部分。如果代码初看不懂的话，建议忽略技术细节，理解其功能即可。

**Comment by C-Harlin** [comment]
18644 is the size of vocabulary
